# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BeetsImporter < Formula
  desc "TUI tool for importing music into beets"
  homepage "https://github.com/dewey/beets-importer"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dewey/beets-importer/releases/download/v1.0.1/beets-importer_1.0.1_darwin_amd64.tar.gz"
      sha256 "b5234461b5e6b62a9a44459ce82eb9bdc1bf3d97ac44b85dba707554ffda0ccc"

      define_method(:install) do
        bin.install "beets-importer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dewey/beets-importer/releases/download/v1.0.1/beets-importer_1.0.1_darwin_arm64.tar.gz"
      sha256 "7f5abc64d5dcab208c0b61cc6e1a144129efe113da4fd597d7ee71a6de3ac02f"

      define_method(:install) do
        bin.install "beets-importer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dewey/beets-importer/releases/download/v1.0.1/beets-importer_1.0.1_linux_amd64.tar.gz"
      sha256 "56a1f3132a731fe66cfb659170fa9d4abbbb0bddfea0fccaf2904ea8aeec2340"
      define_method(:install) do
        bin.install "beets-importer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dewey/beets-importer/releases/download/v1.0.1/beets-importer_1.0.1_linux_arm64.tar.gz"
      sha256 "6a67dc278bb76f0fde271eadcd4f01260d05b848067c18a80d2d3a8cd43ddd11"
      define_method(:install) do
        bin.install "beets-importer"
      end
    end
  end
end
